allowBuilds:
  '@clerk/shared': true
  '@prisma/engines': true
  '@sentry/cli': true
  core-js: set this to true or false
  esbuild: true
  msw: true
  prisma: true
  sharp: true
ignoredBuiltDependencies:
  - sharp
  - unrs-resolver
minimumReleaseAgeExclude:
  - '@prisma/adapter-pg@7.10.0'
  - '@prisma/client-runtime-utils@7.10.0'
  - '@prisma/client@7.10.0'
  - '@prisma/debug@7.10.0'
  - '@prisma/driver-adapter-utils@7.10.0'
  - '@prisma/config@7.10.0'
  - '@prisma/engines@7.10.0'
  - '@prisma/fetch-engine@7.10.0'
  - '@prisma/get-platform@7.10.0'
  - prisma@7.10.0
