import type { Review } from "@/types/review";

export const dummyReviews: Review[] = [
  {
    id: "rev-001",
    packageId: "pkg-maldives",
    userId: "user-001",
    rating: 5,
    title: "Absolute paradise — worth every rupee",
    body: "We celebrated our first anniversary in the Maldives and it was beyond anything we imagined. The overwater villa was stunning, staff were incredibly attentive, and the snorkelling was out of this world. RapidLuxe handled every detail flawlessly.",
    isVerified: true,
    isApproved: true,
    createdAt: new Date("2025-03-14"),
  },
  {
    id: "rev-002",
    packageId: "pkg-bali",
    userId: "user-002",
    rating: 5,
    title: "Bali surpassed all expectations",
    body: "From the rice terrace sunrise to the Uluwatu temple sunset, every moment was magical. Our guide Wayan was exceptional — knowledgeable and warm. The hotel they chose, Alaya Ubud, was spectacular. Highly recommend the RapidLuxe Bali package.",
    isVerified: true,
    isApproved: true,
    createdAt: new Date("2025-02-22"),
  },
  {
    id: "rev-003",
    packageId: "pkg-switzerland",
    userId: "user-003",
    rating: 4,
    title: "Switzerland is stunning but plan well for winter",
    body: "The Alps in winter are breathtaking. Jungfraujoch was a highlight I will never forget. A small hiccup with our Interlaken hotel room category was quickly resolved by the RapidLuxe team. Overall a fantastic trip.",
    isVerified: true,
    isApproved: true,
    createdAt: new Date("2025-01-08"),
  },
  {
    id: "rev-004",
    packageId: "pkg-kerala",
    userId: "user-004",
    rating: 5,
    title: "Kerala is pure magic — perfect family holiday",
    body: "Travelled with my parents and two kids. The houseboat on Alleppey backwaters was the highlight for everyone. Food was authentic and delicious. The Munnar tea estate visit was serene. Excellent value for money.",
    isVerified: true,
    isApproved: true,
    createdAt: new Date("2025-04-03"),
  },
  {
    id: "rev-005",
    packageId: "pkg-dubai",
    userId: "user-005",
    rating: 4,
    title: "Dubai delivered on the glam and then some",
    body: "Desert safari at sunset was unforgettable. Burj Khalifa at night, the Gold Souk, the Frame — Dubai truly never sleeps. The included breakfast at Atlantis was lavish. Would have loved one more day for Miracle Garden.",
    isVerified: true,
    isApproved: true,
    createdAt: new Date("2025-03-29"),
  },
  {
    id: "rev-006",
    packageId: "pkg-santorini",
    userId: "user-006",
    rating: 3,
    title: "Beautiful destination, logistics could be smoother",
    body: "Santorini is undeniably gorgeous. The sunsets from Oia are iconic. However our transfer from the port to Fira was delayed and the room was not the caldera-view one we expected initially. Team did fix it after a call but it cost us half a day.",
    isVerified: false,
    isApproved: true,
    createdAt: new Date("2025-05-01"),
  },
  {
    id: "rev-007",
    packageId: "pkg-rajasthan",
    userId: "user-007",
    rating: 5,
    title: "Royal Rajasthan — felt like actual royalty",
    body: "Staying at Taj Lake Palace in Udaipur and Samode Haveli in Jaipur was an experience of a lifetime. The heritage walk in Jodhpur's blue city and the camel safari in Jaisalmer were incredible. Perfectly curated itinerary.",
    isVerified: false,
    isApproved: true,
    createdAt: new Date("2025-02-10"),
  },
  {
    id: "rev-008",
    packageId: "pkg-singapore",
    userId: "user-008",
    rating: 4,
    title: "Singapore is the perfect family getaway",
    body: "Universal Studios, Gardens by the Bay, and the night safari had my kids absolutely thrilled. The city is immaculate and incredibly safe. Hawker food was a revelation — we skipped the hotel restaurant most nights. Great experience overall.",
    isVerified: false,
    isApproved: true,
    createdAt: new Date("2025-04-18"),
  },
];
